## Ejecutame para ver el contenido ##

print("====================================================")
print("Las expresiones se ejecutan en su mayoria de izquierda a derecha")
print("y segun el orden de precedencia de sus operadores")
print("---------------------------------------------------")
print("La precedencia se determina el orden de ejecución ")
print("esto se conoce como jerarquia de prioridades y son: ")
print("(1) Potencia ( ** ) ")
print("(2) Unarios ( + o - ) ")
print("(3) Multiplicacion, division, modulo ( * , / , // , % ) ")
print("(4) Binarios suma y resta ( + o - ) ")
print("\nLos parentesis () siempre se calculan primero, por ende\npueden cambiar el orden natural de las operaciones")
print("====================================================")

print("\n--------------------------------------------------")
print("----------------------------------------------------")
print("Suma 2*2", end=" : ")
print(2+2)
print("\nSuma con negativos -4 + 4", end=" : ")
print(-4 + 4)
print("\nSuma con flotantes -4. + 8", end=" : ")
print(-4. + 8)

print("\n-------------------------------------------------")
print("---------------------------------------------------")
print("Resta 2-2", end=" : ")
print(2-2)
print("\nResta numeros negativo -4 - 4", end=" : ")
print(-4 - 4)
print("\nResta flotantes 4. - 8", end=" : ")
print(4. - 8)
print("---------------------------------------------------")
print("\nEl operador unario cambia el signo a el numero o expresion")
print("\nOperador unario -1.1", end=" : ")
print(-1.1) 

print("\n-------------------------------------------------")
print("---------------------------------------------------")
print("Multiplicación 2 * 3", end=" : ")
print(2 * 3)
print("---------------------------------------------------")
print("Ejemplo con flotantes")
print("\nMultiplicación 2 * 3.", end=" : ")
print(2 * 3.)
print("\nMultiplicación 2. * 3", end=" : ")
print(2. * 3)
print("\nMultiplicación 2. * 3.", end=" : ")
print(2. * 3.)

print("\n-------------------------------------------------")
print("---------------------------------------------------")
print("División flotante 6 / 3", end=" : ")
print(2 / 3)
print("---------------------------------------------------")
print("Ejemplo con flotantes, el resultado siempre sera flotante")
print("\nDivisión flotante 6 / 3.", end=" : ")
print(6 / 3.)
print("\nDivisión flotante 6. / 3", end=" : ")
print(6. / 3)
print("\nDivisión flotante 6. / 3.", end=" : ")
print(6. / 3.)

print("\n-------------------------------------------------")
print("---------------------------------------------------")
print("División entera 6 // 3", end=": ")
print(6 // 3)
print("---------------------------------------------------")
print("Ejemplo con flotantes, el resultado es redondeado hacia abajo")
print("\nDivisión entera 6 // 3.", end=" : ")
print(6 // 3.)
print("\nDivisión entera 6. // 3", end=" : ")
print(6. // 3)
print("\nDivisión entera 6. // 3.", end=" : ")
print(6. // 3.)
print("---------------------------------------------------")
print("\nEjemplo con negativos -6 // 4", end=" : ")
print(-6 // 4)
print("\nDivisión entera -6 // 4.", end=" : ")
print(-6 // 4)
print("\nDivisión entera 6. // -4", end=" : ")
print(6. // -4)

print("\n-------------------------------------------------")
print("---------------------------------------------------")
print("Residuo o Modulo 2 % 2", end=": ")
print(2 % 2)
print("---------------------------------------------------")
print("\nEjemplo con flotante")
print("Modulo 12 % 4.5", end=" : ")
print(12 % 4.5)

print("\n-------------------------------------------------")
print("---------------------------------------------------")
print("Potencia 2 ** 3", end=" : ")
print(2 ** 3)
print("---------------------------------------------------")
print("Ejemplo con flotantes")
print("\nPotencia 2 ** 3.", end=" : ")
print(2 ** 3.)
print("\nPotencia 2. ** 3", end=" : ")
print(2. ** 3)
print("\nPotencia 2. ** 3.", end=" : ")
print(2. ** 3.)
print("---------------------------------------------------")
print("\nLa pontencia se ejecuta de derecha a izquierda")
print("\nPotencia enlazada 2 ** 2 ** 3", end=" : ")
print(2 ** 2 ** 3)

print("--------------------------------------------------")
print("===================================================")
print("ejercicios de ejemplo")
print("\nOperación print((2 ** 4), (2 * 4.), (2 * 4))", end=" = ")
print((2 ** 4), (2 * 4.), (2 * 4))
print("\nOpreación print((-2 / 4), (2 / 4), (2 // 4), (-2 // 4))", end=" = ")
print((-2 / 4), (2 / 4), (2 // 4), (-2 // 4))
print("\nOperación print((2 % -4), (2 % 4), (2 ** 3 ** 2))", end=" = ")
print((2 % -4), (2 % 4), (2 ** 3 ** 2))

